import { Router, type IRouter } from "express";
import { db, aboutContentTable } from "@workspace/db";

const router: IRouter = Router();

function serialize(a: typeof aboutContentTable.$inferSelect) {
  return {
    greetingImageUrl: a.greetingImageUrl,
    greetingMessageKo: a.greetingMessageKo,
    greetingMessageEn: a.greetingMessageEn,
    greetingMessageJa: a.greetingMessageJa,
    greetingMessageZh: a.greetingMessageZh,
    greetingMessageVi: a.greetingMessageVi,
    greetingSignatureKo: a.greetingSignatureKo,
    greetingSignatureEn: a.greetingSignatureEn,
    greetingSignatureJa: a.greetingSignatureJa,
    greetingSignatureZh: a.greetingSignatureZh,
    greetingSignatureVi: a.greetingSignatureVi,
    historyItems: a.historyItems,
    worldwideImageUrl: a.worldwideImageUrl,
    worldwideIntroKo: a.worldwideIntroKo,
    worldwideIntroEn: a.worldwideIntroEn,
    worldwideIntroJa: a.worldwideIntroJa,
    worldwideIntroZh: a.worldwideIntroZh,
    worldwideIntroVi: a.worldwideIntroVi,
    worldwideItems: a.worldwideItems,
    companyDescKo: a.companyDescKo,
    companyDescEn: a.companyDescEn,
    companyDescJa: a.companyDescJa,
    companyDescZh: a.companyDescZh,
    companyDescVi: a.companyDescVi,
    philosophyImageUrl: a.philosophyImageUrl,
    philosophyHeadingKo: a.philosophyHeadingKo,
    philosophyHeadingEn: a.philosophyHeadingEn,
    philosophyHeadingJa: a.philosophyHeadingJa,
    philosophyHeadingZh: a.philosophyHeadingZh,
    philosophyHeadingVi: a.philosophyHeadingVi,
    philosophyIntroKo: a.philosophyIntroKo,
    philosophyIntroEn: a.philosophyIntroEn,
    philosophyIntroJa: a.philosophyIntroJa,
    philosophyIntroZh: a.philosophyIntroZh,
    philosophyIntroVi: a.philosophyIntroVi,
    philosophyCards: a.philosophyCards,
    founderHeadingKo: a.founderHeadingKo,
    founderHeadingEn: a.founderHeadingEn,
    founderHeadingJa: a.founderHeadingJa,
    founderHeadingZh: a.founderHeadingZh,
    founderHeadingVi: a.founderHeadingVi,
    founderIntroKo: a.founderIntroKo,
    founderIntroEn: a.founderIntroEn,
    founderIntroJa: a.founderIntroJa,
    founderIntroZh: a.founderIntroZh,
    founderIntroVi: a.founderIntroVi,
    founderOutroKo: a.founderOutroKo,
    founderOutroEn: a.founderOutroEn,
    founderOutroJa: a.founderOutroJa,
    founderOutroZh: a.founderOutroZh,
    founderOutroVi: a.founderOutroVi,
    founderAreas: a.founderAreas,
    whyDostacItems: a.whyDostacItems,
    directionsAddressKo: a.directionsAddressKo,
    directionsAddressEn: a.directionsAddressEn,
    directionsAddressJa: a.directionsAddressJa,
    directionsAddressZh: a.directionsAddressZh,
    directionsAddressVi: a.directionsAddressVi,
    directionsMapEmbed: a.directionsMapEmbed,
    directionsImageUrl: a.directionsImageUrl,
  };
}

const EMPTY = {
  greetingImageUrl: null,
  greetingMessageKo: "",
  greetingMessageEn: "",
  greetingMessageJa: "",
  greetingMessageZh: "",
  greetingMessageVi: "",
  greetingSignatureKo: "",
  greetingSignatureEn: "",
  greetingSignatureJa: "",
  greetingSignatureZh: "",
  greetingSignatureVi: "",
  historyItems: [],
  worldwideImageUrl: null,
  worldwideIntroKo: "",
  worldwideIntroEn: "",
  worldwideIntroJa: "",
  worldwideIntroZh: "",
  worldwideIntroVi: "",
  worldwideItems: [],
  companyDescKo: "",
  companyDescEn: "",
  companyDescJa: "",
  companyDescZh: "",
  companyDescVi: "",
  philosophyImageUrl: null,
  philosophyHeadingKo: "",
  philosophyHeadingEn: "",
  philosophyHeadingJa: "",
  philosophyHeadingZh: "",
  philosophyHeadingVi: "",
  philosophyIntroKo: "",
  philosophyIntroEn: "",
  philosophyIntroJa: "",
  philosophyIntroZh: "",
  philosophyIntroVi: "",
  philosophyCards: [],
  founderHeadingKo: "",
  founderHeadingEn: "",
  founderHeadingJa: "",
  founderHeadingZh: "",
  founderHeadingVi: "",
  founderIntroKo: "",
  founderIntroEn: "",
  founderIntroJa: "",
  founderIntroZh: "",
  founderIntroVi: "",
  founderOutroKo: "",
  founderOutroEn: "",
  founderOutroJa: "",
  founderOutroZh: "",
  founderOutroVi: "",
  founderAreas: [],
  whyDostacItems: [],
  directionsAddressKo: "",
  directionsAddressEn: "",
  directionsAddressJa: "",
  directionsAddressZh: "",
  directionsAddressVi: "",
  directionsMapEmbed: null,
  directionsImageUrl: null,
};

router.get("/public/about", async (_req, res) => {
  const [row] = await db
    .select()
    .from(aboutContentTable)
    .orderBy(aboutContentTable.id)
    .limit(1);
  res.json(row ? serialize(row) : EMPTY);
});

export default router;
export { serialize as serializeAbout, EMPTY as EMPTY_ABOUT };
