// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/dostac/About.tsx": () => import("../components/mockups/dostac/About.tsx"),
  "./components/mockups/dostac/Contact.tsx": () => import("../components/mockups/dostac/Contact.tsx"),
  "./components/mockups/dostac/Home.tsx": () => import("../components/mockups/dostac/Home.tsx"),
  "./components/mockups/dostac/Production.tsx": () => import("../components/mockups/dostac/Production.tsx"),
  "./components/mockups/dostac/Products.tsx": () => import("../components/mockups/dostac/Products.tsx")
};
